### PR TITLE
Use pipes for event queues

### PR DESCRIPTION
**Pull request by jacobly0**
I was getting a reproducible issue where loading a save state would cause the game to receive incorrect joystick inputs.  I didn't debug the issue too much, but I suspect it is because checkpoints don't save and restore fd offsets.  However, using pipes is much cleaner and fixes the issue anyway.  Also, support evdev ioctls on the corresponding jsdev, because I saw a game trying to use one of the implemented ioctls on the jsdev.

### CODE REVIEW

**Comment by clementgallet** [comment]
Nice!

Well, savestates do save fd offsets, but only from files opened by the game. I totally forgot about fds created by libtas itself...

Anyway, I wanted to replace that code with pipes, but I have one concern: pipe buffer lies outside the process memory, so it is not stored in savestates. If the game does not empty the pipe every frame, then we have a problem?

Would emptying the pipe before pushing new events make sense? It would mean that users cannot buffer inputs like they can with the native game?

**Comment by jacobly0** [comment]
In reference to #163, a file stream never blocks at EOF, regardless of blocking mode.  However, even ignoring that issue, the old `write_*dev` code did not update the file state atomically, so asynchronous reading would still be an issue.  Emptying the pipe before loading a savestate would mean that inputs could still be buffered, just not past save states.  Alternatively, when events are not being handled asynchronously, the pipes contents could be dumped into memory before loading a savestate, and written back into the pipe after a savestate is loaded.  In the asynchronous event handling case, a savestate transition can presumably never happen while the pipe is non-empty because the writes would block until the data has been read.

**Comment by clementgallet** [comment]
Yes, I think the right way to go is to store the pipe content in memory before a savestate and restore it back.

I'm confused by your last sentence. Why would the pipe writing even block? Or is it what you are suggesting to fix the async event handle case (to make the pipe writing waits until all data has been read)?

**Comment by jacobly0** [comment]
I implemented saving of pipe contents with checkpoints, and seems to work great other than an unrelated crash that was still reproducible before this commit.  In theory this could also be used for pipes created by the game, but it would need to support closing the ends of user pipes separately and I'm not sure that games have any reason to create pipes.

My last point ended up being moot because all of the threads are already suspended while the pipe contents are being saved and restored.  Meanwhile, I am still working on figuring out the best way to handle asynchronous events.

**Comment by jacobly0** [comment]
I added an option to block waiting for asynchronous events to be processed.  I can't actually test it, but the idea is to send all the events for the current frame, then wait for all of them to be read from the pipe.  However, if we start the frame at that point, there's a race against the event processing finishing.  Therefore, I send a dummy synchronize event and wait for that event to get read, at which point the preceding events should hopefully have finished processing on the event thread.  Hopefully, games won't have the event queue open until the event thread is running.  If this is not the case, we can trying skipping the sync logic if no events were sent that frame, and it would just be up to the user to not send any events too early.

**Pull request merged**
