### PR TITLE
Steam API stubs to get The Talos Principle to run

### PR DESCRIPTION
**Pull request by iamgreaser**
Mostly fixes issue #181 . Not TASable yet, but the game runs OK with a few libTAS settings changes.

- Added ISteamUser::StopVoiceRecording() stub and stubs before it
- Added SteamController stubs

In order to get Talos to run you will need the following non-defaults:

- Runtime -> Virtual Steam client ON
- Runtime -> Time tracking -> Primary thread -> gettimeofday() ON
- Runtime -> Debug -> Native events ON
- Video -> OSD -> all checkboxes OFF (this is why I say this *mostly* fixes the issue, because I would like to see the OSD working)

TODO before merging:

`library/steam/isteamuser.cpp`, method `ISteamUser::GetUserDataFolder`: I use `getcwd` from `unistd.h` and then return it. I suspect what we actually want is a config path that can be set from maybe File -> Executable Options.

### CODE REVIEW

**Comment by jacobly0** [comment]
For the record, the Steam Controller API this PR implements is an old version that won't work with The Talos Principle, which uses `SteamController003`, which is why TAS events don't work.  However, even if I implement the correct Steam Controller API, I can't actually get the TAS events to get transmitted to libtas.so yet.

**Comment by clementgallet** [comment]
I fix we would want a specific folder for Steam data, probably in "~/.local/share/libtas/steam/" like the other data. It would also be used for storing remote storage (usually steam save files), which are for now stored in `/tmp`

**Comment by iamgreaser** [comment]
> I think we would want a specific folder for Steam data, probably in `~/.local/share/libtas/steam/` like the other data.

Good idea. I'll take a look into that.

In the meantime I've updated the branch. At the moment it seems a mouse click will crash Talos but keyboard inputs are fine.

**Comment by iamgreaser** [comment]
OK, this PR now takes the Steam path from `~/.local/share/libTAS/steam/` or whatever the appropriate home data dir is for libTAS stuff. Some parts are a tad ugly and I'm not quite sure how best to arrange things yet. But at least we've now got something that can be built upon which would lend itself well to having the path as a configurable option.

Dropping the draft status of this. Review away.

**Pull request merged**
