### PR TITLE
Markers

### LINKED ISSUE #548: Ability to add markers to savestates and/or frames
When doing complex non-linear comparisons across several branches, it's very easy to get lost, especially if you have to keep creating newer branches just to have backups. Without notes which branch is what it's very hard to figure out which to go back to in order to tweak the strats, and what game state they contain.

To display those notes, the easiest way would probably be to simply show a popup when hovering on a frame that has the branch with a note.

In my use case, adding notes just to savestates/branches would be enough, but maybe users would want to add markers to regular frames. Maybe overall that would be a better solution, since to add/display the notes, actions for branches and frames would be the same, and being able to add them to any frame would cover more use cases.

### PR DESCRIPTION
**Pull request by vadosnaprimer**
will close #548

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
@clementgallet I was unable to figure out how to make marker text from the currently selected frame appear on the screen. Can you help please?

**Comment by vadosnaprimer** [comment]
Thanks! Still need to figure out how to show and hide markers without having to advance frames.

**Comment by clementgallet** [comment]
By the way, the fix was that the Qt signal and slot functions must have an identical signature.

**Comment by clementgallet** [comment]
Also, middle-left the default location that you want for markers?

**Comment by vadosnaprimer** [comment]
> By the way, the fix was that the Qt signal and slot functions must have an identical signature.

Yeah I've never worked with Qt before.

> Also, middle-left the default location that you want for markers?

All the corners are occupied, and marker use would probably be infrequent for most users, so I think middle left is the best place.

**Comment by clementgallet** [comment]
> Oh I also plan to allow editing markers via double-click on frame column.

Don't we want to show the marker text in a toolbox when mouse cursor is hovering the frame?

**Comment by vadosnaprimer** [comment]
That would be great too (you mean tooltip?)

**Comment by clementgallet** [comment]
> That would be great too (you mean tooltip?)

yes!

**Comment by clementgallet** [comment]
Sorry I failed pushing more commit here, so I merged into master already

**Pull request closed without merging**
