### PR TITLE
Support SDL Dynamic API.

### PR DESCRIPTION
**Pull request by jacobly0**
SDL 2.0.2 added a [feature](https://plus.google.com/+RyanGordon/posts/TB8UfnDYu4U) to allow dynamically linking SDL functions even when it was statically linked.  This takes advantage of that feature by setting `SDL_DYNAMIC_API` to libtas.so which causes SDL to call our `SDL_DYNAPI_entry` the first time any SDL function is called.  We start by dispatching to the original `SDL_DYNAPI_entry` which fills in the jump table with all of the original functions, which are not otherwise accessible through dynamic linking.  This means that our normal `LINK_NAMESPACE` stuff is not going to work, so instead we copy out all of the original SDL functions referenced by libtas.so from the jump table to their global pointers in `namespace orig`.

In order to do that, I had to make `DECLARE_ORIG_POINTER` not be `static` so that we can override all of the SDL original pointers once and for all.  However, this means also having a `DEFINE_ORIG_POINTER` and using the define variant exactly once in the entire library, and the declare everywhere else.  I'm not super happy with that, but it works for now at least.  Really, the declarations should be included from headers and the definitions grouped somewhere specific.

Lastly, we copy pointers to our hook functions over the jump table entries, effectively overriding those functions.  The main disadvantage of how I implemented this is that [sdlhooks.h](https://github.com/jacobly0/libTAS/blob/797801bcab7a5d43489dc0e5a83e8507731bea9a/src/library/sdlhooks.h) needs to be kept up to date with all SDL2 functions that are used and/or overridden in the entire library, however the alternative of doing things automatically with dynamic linking was causing issues.  In theory you could have an array of all the SDL function names in ABI order, and dynamically find which ones are defined in libtas.so to override, and which ones have pointers in `namespace orig` to save.  Meanwhile, it is very easy to update sdlhooks.h, it is just a matter of remembering to do so.

### CODE REVIEW

**Comment by clementgallet** [comment]
Wow, I didn't know such functionality was present in SDL2.

First, I wonder what was your motivation behind this change? Does it fix something (or will fix some untested games), or do you find it cleaner?

It is possible that it would make Iconoclasts to work. The game uses SDL2, and is bundled with `libSDL2-2.0.so.0`, but no SDL function is hooked by libTAS. libSDL2 does not show in `$ ldd Chowdren`. When reading the symbols of the game binary, it shows like that, but I'm not sure what does it mean:
```
$ readelf -Ws Chowdren | grep SDL
   273: 0000000000e1e8b0    15 FUNC    GLOBAL DEFAULT   13 SDL_JoystickGetGUIDFromString
   275: 0000000000e1f780     9 FUNC    GLOBAL DEFAULT   13 SDL_sin
   286: 0000000000e1fa10     9 FUNC    GLOBAL DEFAULT   13 SDL_SetThreadPriority
   287: 0000000000e20390     9 FUNC    GLOBAL DEFAULT   13 SDL_Vulkan_GetInstanceExtensions
   291: 0000000000e1e370     9 FUNC    GLOBAL DEFAULT   13 SDL_HasEvent
[...]
```
With the PR change, I'm getting this on libTAS log:
```
[libTAS f:0] Thread 24298 (main) dlopen call with file /home/clement/libtas-1.3.2/build/libtas.so
[libTAS f:0] Thread 24298 (main) dlsym call with function SDL_DYNAPI_entry
[libTAS f:0] Thread 24298 (main) SDL_DYNAPI_entry call.
[libTAS f:0] Thread 24298 (main) Imported symbol SDL_DYNAPI_entry function : 0xe20f60
```
But then it freezes in:
```
(gdb) bt
#0  0x0000000000e1df60 in SDL_Init ()
#1  0x00000000004c645b in _start ()
```

Also, it breaks Super Meat Boy (which is more of the game's fault actually). The game has external symbols (I guess function pointers) whose names match the names of OpenGL functions:
```
nm -C SuperMeatBoy | grep gl
000000000055d110 T glActiveTexture
000000000055d120 T glAlphaFunc
000000000055d370 T glBindBufferARB
000000000055d420 T glBindFramebufferEXT
000000000055d3e0 T glBindRenderbufferEXT
000000000055d130 T glBindTexture
000000000055d140 T glBlendEquation
```
So, when we call `LINK_NAMESPACE(glActiveTexture, "GL");` in our code, we first search for a symbol using `RTLD_DEFAULT`, which returns the above symbol instead of the symbol in `libGL.so`. Is there a reason why you switched `RTLD_DEFAULT` and `RTLD_NEXT`?

**Comment by clementgallet** [comment]
About Iconoclasts, the problem is that in `sdldynapi.cpp`, when hooking all SDL functions:
```
#define SDL_HOOK(FUNC) SDL_LINK(FUNC); entries[index::FUNC] = reinterpret_cast<void *>(FUNC);
```
`FUNC` is both a symbol in the game executable and in libtas.so, and in this case, it actually refers to the game executable symbol. I could fix this by doing the following:

```
void* handle = dlopen("libtas.so", RTLD_LAZY);
#define SDL_HOOK(FUNC) SDL_LINK(FUNC); entries[index::FUNC] = dlsym(handle, #FUNC);
```
But it seems very wrong and unnecessary. Loading `libtas.so` does not mean it will execute static code and initialize static variables (again)? Won't there be two instances of the library in memory? It seems to work fine though, so I'm confused.

**Comment by jacobly0** [comment]
My motivation is that modern unity games are statically linked with SDL2, and so this is a way to hook the non-dynamic symbols.  I switched `RTLD_DEFAULT` and `RTLD_NEXT` because I was having issues finding the original `SDL_DYNAPI_entry` but I realize now that we could just be using the external library's version which works after fixing another bug.  However, I'm still not sure what is the right thing to do, whether to prefer symbols from the executable itself or an external library.  The Super Meat Boy issue can possibly be fixed by checking whether the symbol refers to code and using `RTLD_NEXT` if that is the case.

To answer your other questions, by default, `dlopen` does not create a new instance of the shared library, instead it just returns the already loaded library.  You can only have multiple copies of the same shared object in memory if they are in different namespaces.  In addition, you can do `void *handle = dlopen(nullptr, RTLD_LAZY);` which specifically returns a handle to the current library (aka. the one that contains the return address of the `dlopen` call).  It appears that the game I was testing with doesn't export the SDL symbols, which I was incorrectly assuming would always be the case.

**Comment by jacobly0** [comment]
I'm looking at Super Meat Boy and it has opengl function stubs that dispatch to a C++ global function pointer.  The global function pointer is being loaded with SDL_GL_GetProcAddress, so this could just be an issue with SDL hooks?

**Comment by clementgallet** [comment]
I tried using `dlopen(nullptr, RTLD_LAZY);` first, and it didn't work. From the man page it says that `If  filename is NULL, then the returned handle is for the main program.`

**Comment by jacobly0** [comment]
Yeah sorry, I keep getting it confused with `RTLD_DEFAULT` which is also a null pointer.

**Comment by jacobly0** [comment]
Ok yeah, I think I understand now.  Super Meat Boy is dynamically loading our hooks into function pointers and so when we try to use the program's stubs, we would end up recursing.  In any case, I'm still confused by the code in `link_function`.  If we try `RTLD_DEFAULT` first, then it makes sense to check if it is our own symbol.  However if we do `RTLD_NEXT` first, then it shouldn't be possible to get our own symbol, so I guess we might as well just use `RTLD_NEXT`.  Now that that is working for me too, let me know if there's another game it breaks.

**Comment by clementgallet** [comment]
I added the code to check if it was our own symbol some time ago, because I was randomly getting recursive calls after hooking a function. Indeed, I was getting my own symbol with `RTLD_NEXT`, so it was for debugging purpose. But I didn't encounter this in a while, so maybe I fixed it somehow.

**Pull request merged**
