### PR TITLE
A couple improvements to debugger support

### PR DESCRIPTION
**Pull request by jakobrs**
The first commit:

The "Launch with GDB" button has a dropdown where you can select to use either gdb or lldb.

image

The choice of whether to use gdb or lldb is stored the global libTAS.ini configuration file.

---

The second commit:

Adds a "Raise SIGINT upon game launch" option that makes `libtas::main` call `raise(SIGINT)` after connecting to libTAS. Useful for setting breakpoints and similar.

### CODE REVIEW

**Comment by clementgallet** [comment]
Nice! Two comments:
* Don't we want "Raise SIGINT" inside `Runtime > Debug` menu?
* Maybe we want to save the debugger choice inside the game's config file?

**Comment by jakobrs** [comment]
> Don't we want "Raise SIGINT" inside `Runtime > Debug` menu?

I agree, I've changed it now.

> Maybe we want to save the debugger choice inside the game's config file?

The reason I did it this way is because I figure that the choice of debugger is mostly up the preferences of the user, and not something that depends on the game. But if you disagree I can change it.

**Comment by clementgallet** [comment]
There's a general preferences file (libTAS.ini) that current only holds the list of previously executed games. Maybe we can save that in it?

**Comment by jakobrs** [comment]
That's what this PR does.

**Comment by clementgallet** [comment]
Oh, I missed that, sorry.

**Pull request merged**
