### PR TITLE
Remove http: links in the readme

### PR DESCRIPTION
**Pull request by jbzdarkid**

### CODE REVIEW

**Comment by LukeSaward1** [comment]
This PR breaks TASVideos links, as https is not supported.
The other HTTPS links are fine.

**Comment by InfoTeddy** [comment]
> This PR breaks TASVideos links

Not unless you're still in 2021. TASVideos is going to become HTTPS on New Year's.

**Comment by ViGadeomes** [comment]
Most of the links to TASvideos don't work, please change them by :
15 - https://tasvideos.org/EmulatorResources/LibTAS/GameCompatibility 
95 - https://tasvideos.org/EmulatorResources/LibTAS/MenuOptions
97 - https://tasvideos.org/EmulatorResources/LibTAS/Usage

**Comment by clementgallet** [comment]
Thanks!

**Pull request merged**
